### ISSUE TITLE
Brak pliku README - Czy to taka trudna rzecz?

### ISSUE THREAD

**Issue by Maciek99** [Stasiek-Stepka-aka-Mustang/BeatFlipper#1]
Hmm, wydawało mi się, że to oczywiste, ale widzę, że muszę przypomnieć - brakuje pliku README. Właśnie takiego małego, pomocnego pliku dla tych, którzy chcieliby pomóc w utrzymaniu tego projektu

**Comment by Stasiek-Stepka-aka-Mustang** [comment]
Przeoczyłem ten krok, dziękuje za uwagę! Niedługo wrzucę ten pliczek!

**Comment by Stasiek-Stepka-aka-Mustang** [comment]
Plik wrzucony!

**Comment by Stasiek-Stepka-aka-Mustang** [comment]
Plik wrzucony!
